version: '3.5'

services:
    php:
        build: ./../../
        ports:
          - "80:80"
          - "443:443"
        container_name: scoutswetteren-php-container
        volumes:
         - ../../../files:/var/www/scoutswetteren.dev/files
         - ../../../pirate:/var/www/scoutswetteren.dev/pirate
         - ../../../public:/var/www/scoutswetteren.dev/public
         - ./config.php:/var/www/scoutswetteren.dev/pirate/config.php
         - ./config.private.php:/var/www/scoutswetteren.dev/pirate/config.private.php
         - ./nginx.conf:/etc/nginx/conf.d/site.conf
         - ./certs:/etc/nginx/certs/scoutswetteren.dev
        environment:
         - DEBUG=1
        security_opt:
         - seccomp:unconfined
        privileged: true