version: '3.5'

services:
    php:
        external_links:
         - "scouts-mysql:db"
        build: ./../../
        ports:
          - "80:80"
          - "443:443"
        container_name: scoutssintjan-php-container
        volumes:
         - ../../../files:/var/www/scoutssintjan.dev/files
         - ../../../pirate:/var/www/scoutssintjan.dev/pirate
         - ../../../public:/var/www/scoutssintjan.dev/public
         - ./config.php:/var/www/scoutssintjan.dev/pirate/config.php
         - ./config.private.php:/var/www/scoutssintjan.dev/pirate/config.private.php
         - ./nginx.conf:/etc/nginx/conf.d/site.conf
         - ./certs:/etc/nginx/certs/scoutssintjan.dev
        environment:
         - DEBUG=1
        security_opt:
         - seccomp:unconfined
        privileged: true

networks:
    default:
          external: 
               name: scouts
