folder: "scoutswetteren.be"
server: "root@scoutswetteren.be"
e-mail: "simon.backx@scoutswetteren.be"
mysql:
  username: root
  password: root
  database: scouts
letsencrypt:
  - "scoutswetteren.be"
  - "www.scoutswetteren.be"
  - "files.scoutswetteren.be"
certificate-name: "scoutswetteren.be-0001"
pirate-config-location: "docker/environments/scoutswetteren.dev"
sass: "pirate/themes/prins-boudewijn/scss/main.scss:public/css/prins-boudewijn.css pirate/themes/sint-jan/scss/main.scss:public/css/sint-jan.css pirate/themes/sint-jan/scss/print/print.scss:public/css/sint-jan.print.css pirate/themes/prins-boudewijn/scss/print/print.scss:public/css/prins-boudewijn.print.css pirate/themes/sint-jan/scss/letter/letter.scss:public/css/sint-jan.letter.css pirate/themes/prins-boudewijn/scss/letter/letter.scss:public/css/prins-boudewijn.letter.css"
